### ISSUE TITLE
TypeError: generate_step() got an unexpected keyword argument 'temp' on v0.21.0

### ISSUE THREAD

**Issue by notnotrishi** [ml-explore/mlx-examples#1201]
Getting an error with temp after upgrading to 0.21.0 from pypi

Example code:
```
from mlx_lm import load, generate

model, tokenizer = load("mlx-community/gemma-2-2b-it-4bit")

prompt = "Write a story about Einstein"

messages = [{"role": "user", "content": prompt}]
prompt = tokenizer.apply_chat_template(
    messages, add_generation_prompt=True
)

text = generate(model, tokenizer, prompt=prompt, verbose=True, temp=0.3, max_tokens=1000)
```
Error:
```
rishi@Rishis-Air mlxcli % python3 test.py   
Fetching 7 files: 100%|████████████████████████| 7/7 [00:00<00:00, 50708.34it/s]
==========
Traceback (most recent call last):
  File "/Users/rishi/Projects/mlxcli/test.py", line 12, in <module>
    text = generate(model, tokenizer, prompt=prompt, verbose=True, temp=0.3, max_tokens=1000)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mlx_lm/utils.py", line 593, in generate
    for response in stream_generate(model, tokenizer, prompt, **kwargs):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/mlx_lm/utils.py", line 519, in stream_generate
    token_generator = generate_step(prompt, model, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: generate_step() got an unexpected keyword argument 'temp'
```

**Comment by notnotrishi** [comment]
addl info:
```
pip3 show mlx-lm
Name: mlx-lm
Version: 0.21.0
Summary: LLMs on Apple silicon with MLX and the Hugging Face Hub
Home-page: https://github.com/ml-explore/mlx-examples
Author: MLX Contributors
Author-email: mlx@group.apple.com
License: MIT
Location: /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages
Requires: jinja2, mlx, numpy, protobuf, pyyaml, transformers
Required-by: 
```

**Comment by awni** [comment]
Yes, that was marked deprecated in previous versions and removed entirely in 0.21.

If you want to use a sampler, use the sampling utils like so:

```
sampler = make_sampler(temp)
```

And pass the `sampler` to `generate`.

For `temp` it might be worth making an exception and allowing it as a kwarg to `generate` but for the other sampling parameters, one should make a sampler ahead of time and pass it into `generate`. Decoupling samling from the generation functions keeps things a lot cleaner.

**Comment by notnotrishi** [comment]
oops! just saw the change in previous version. passing sampler fixes it.
